### ISSUE TITLE
Issue loading the placeholder image with an adblocker active

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#180]
It seems that the placeholder image on the example `index.html` file doesn't load if we have an adblocker enabled:
<img width="1031" alt="screen shot 2019-01-24 at 08 45 34" src="https://user-images.githubusercontent.com/11976836/51662552-74766000-1fb4-11e9-9d0a-117b6c33b215.png">

**Comment by teriyakigod2** [comment]
Could you please specify your environment (browser, adblock plugin), because with Adblock Plus for FF works well.
![image](https://user-images.githubusercontent.com/27350480/51905229-bdbe1980-23d1-11e9-8c34-048c5025fc3a.png)

![image](https://user-images.githubusercontent.com/27350480/51905263-d2021680-23d1-11e9-89b8-6df21c39abc6.png)

**Comment by filfreire** [comment]
Closing this issue, since it's unrelated to Tacit per-se, and depends on user specific browser config.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#180` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
